setup.py, src/rpdk/core/__init__.py, src/rpdk/core/project.py, tests/test_project.py
*Description of changes:* Add back in the waiter since we are having some issues with the newly released type registration waiter.
=> Add waiter

README.rst
*Description of changes:* Change markdown codeblock to reStructuredText
=> README formatting

README.rst
*Issue #, if available:* #355 
*Description of changes:*  Adding in a list of supported plugins under the plugin section for some clarity.
=> Adding supported plugins to readme

src/rpdk/core/project.py, src/rpdk/core/upload.py
*Description of changes:* Bit of additional logging that will help with debugging.
=> Extra logging (region, stack IDs)

README.rst
Adds doc links to README and fixes title
=> Adds doc links to README and fixes title

.pre-commit-config.yaml, .travis.yml
*Description of changes:* Creating a draft PR to test out travis-ci for the main repo, as I am testing by adding commits to this branch. Will mark as ready once it looks up to snuff with the other travis jobs in the other repos
=> Adding travis ci

src/rpdk/core/data/managed-upload-infrastructure.yaml
*Issue #, if available:* n/a
Enforce "secure transport" bucket policy on the artifacts bucket created in the user account
=> Enforce secure transport policy on artifacts bucket

src/rpdk/core/data/schema/README.md
*Issue #, if available:* n/a
README.md is updated to stay in sync with the master version in aws-cloudformation-resource-schema repository
=> Bring schema/README.md in sync with aws-cloudformation-resource-schema

src/rpdk/core/__init__.py
*Description of changes:* This is to bump the version in order to release a new version for the doc generation and the variable support for contract tests along with other fixes. 
=> Bump version for release

README.md
*Issue #, if available:* https://github.com/aws-cloudformation/cloudformation-cli/issues/412
*Description of changes:* Document `cfn test` and how to run a single test
=> Document `cfn test`

src/rpdk/core/contract/resource_client.py, tests/contract/test_resource_client.py
*Description of changes:* Create, Update, Delete Handler should complete in 60 seconds. Read and List handler should complete in 30 seconds. Asserting this in contract test
I misconfigured my head repo and it does not allow me to push to the contract_test branch: https://github.com/aws-cloudformation/cloudformation-cli/pull/443/commits/4c780955ddb66e0191738987a572644d6e6e773f
I have created a new pull request. I have linked my origin PR above. 
=> Contract test

src/rpdk/core/__init__.py
=> bumped version for release -> 0.1.4

docs/README.md, docs/RESOURCE_MODELLING.md
*Description of changes:* In response to a number of [twitter](https://twitter.com/ben11kehoe/status/1271853414599794688) [threads](https://twitter.com/rchrdbyd/status/1271607833902145541) I'm opening this PR to start a GitHub pages site for this repo, with the aim of crowd-sourcing guidance on CloudFormation Resource Provider development.
=> Initial docs source

docs/README.md
*Description of changes:* Using relative links for GitHub pages publishing.
=> Use relative links

docs/README.md
*Description of changes:* Fixes relative link to repo root `README.md`
=> Fix relative link

src/rpdk/core/jsonutils/utils.py, tests/jsonutils/test_flattener.py
added the logic to merge subschemas for multiple types:
input schema:
```json
{
"definitions": {
"obj": {
"type": "boolean"
}
},
"Property1": {
"oneOf": [
{
"type": "string",
"minLength": 4
},
{
"type": "object"
},
{
"type": "integer",
"minimum": 2
},
{
"$ref": "#/definitions/obj"
}
]
}
}
}
```
converged schema:
```json
"type": ["string", "object", "integer", "boolean"]
```
=> added logic to merge subschemas for key type

docs/CLOUDFORMATION_CLI.md, docs/README.md
*Description of changes:* Failed to get relative links working in the Jekyll pages site, so surrendering.
=> Copying README.md into docs folder

README.md
include python plugin in readme 
=> update readme -  include python plugin install

setup.py, tests/test_project.py
*Description of changes:* `master` branch had issues in `pre-commit` locally. This PR cleans up the branch.
=> Fixing pre-commit errors

src/rpdk/core/__init__.py
=> bumped version for release -> 0.1.5

README.md
Adding a command to the README because I will totally forget and want to look it up later...
=> Adding a command to the README

src/rpdk/core/templates/template.yml
increasing timeout for local template.yml to allow network latency. 60s might cause some contract tests to fail local sam testing
=> increased local testing timeout

src/rpdk/core/__init__.py
*Issue #, if available:* 
*Description of changes:* Bumping the version for cloudformation-cli to release the latest changes
=> Bump version to 0.1.6

.travis.yml
*Issue #, if available:* https://github.com/aws-cloudformation/cloudformation-cli/pull/539
This code change allows us to release cloudformation-cli for every tags change
For some reason the change got pushed to the travis branch but does not show up in the PR. Creating a new branch to enable the code to be pushed.
=> Automatic release to PyPI when tags are released

src/rpdk/core/contract/resource_client.py, src/rpdk/core/contract/suite/handler_commons.py, src/rpdk/core/contract/suite/handler_create.py, src/rpdk/core/contract/suite/handler_delete.py, src/rpdk/core/contract/suite/handler_update.py, tests/contract/test_resource_client.py
This CR checks if the input to the create/update handler is equal to the output. 
* WriteOnly Properties are removed from the input as the output should not have writeOnlyProperty. 
* ReadOnlyProperties are removed from the output as the input should not have those. 
* CreateOnly Properties are removed from input and output because, these values can be generated by the handler or entered from the customer. 
*Test*
* Ran these tests against CloudWatch Alarm resource:
```
========================================================================================================================================================================================================================================= test session starts …
```
=> Assert input to the handler is equal to the output

.gitignore, src/rpdk/core/contract/suite/contract_asserts.py
* Ignore rpdk.log.1 file when generated
* remove unneeded LOG messages
=> ignore generated rpdk.log.1 file, removing unneeded log messages

src/rpdk/core/project.py, tests/test_project.py
changing the inputs folder gen to example inputs
=> inputs -> example imputs

README.md
*Issue #, if available:* Closing #573 
=> added cfn submit section to README

.coveragerc, src/rpdk/core/contract/resource_client.py
*Description of changes:* Scoping down logging information
=> Reduce the data being logged

src/rpdk/core/__init__.py
=> Bump version 0.1.11

src/rpdk/core/jsonutils/flattener.py, src/rpdk/core/jsonutils/utils.py, src/rpdk/core/project.py, tests/data/schema/target_output/multityped.md, tests/data/schema/valid/valid_multityped_property.json, tests/jsonutils/test_flattener.py, tests/test_project.py
Circular reference support;
Schema:
```json
{
"typeName": "SAMPLE::AMZN::RESOURCE",
"description":"sample",
"definitions": {
"ConfigurationUnit": {
"type": "object",
"additionalProperties": false,
"Classification": {
"type": "string"
},
"Configurations": {
"type": "array",
"uniqueItems": true,
"items": {
"$ref": "#/definitions/ConfigurationUnit"
}
}
}
}
},
"Id": {
"type": "string"
},
"Configurations": {
"description": "The list of configurations supplied for an EMR cluster instance group. You can specify a separate configuration for each instance group (master, core, and task).",
"type": "array",
"uniqueItems": true,
"items": {
"$ref": "#/definitions/ConfigurationUnit"
}
}
}
}
```
Docs:
README.md
```md …
```
=> Circular Reference Support

src/rpdk/core/__init__.py
=> Bump to version 0.1.13

src/rpdk/core/__init__.py
*Issue #, if available:* 
*Description of changes:* Bumping version for release so that I can use the version in https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/328, a PR that depends on the changes added in #621. Once this is released I can use the functionality in the java plugin.
=> Bump for release

tests/fragments/test_generator.py
The unit test in question was depending on a specific folder to exist. There are other tests which will create that folder, but I suspect the tests are executed in a deterministic order. Fixed this by changing the test to use a shared method which includes the creation of said folder.
=> Fix flaky unit test

src/rpdk/core/data/schema/meta-schema.json
*Issue #, if available:* #650
*Description of changes:* Removes propertyTransform from our local copy of draft-07 schema. We created this copy to support local development but should not be modified.  
=> Remove propertyTransform from metaschema

src/rpdk/core/data/examples/resource/initech.tps.report.v1.json
*Description of changes:* Add tags to the example schema. Follows our [best practices](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html).
=> Add tags to example resource

README.md
https://github.com/aws-cloudformation/cloudformation-cli/blob/c53c6da5a28132f49695d0560b73d1224efde629/src/rpdk/core/submit.py#L35-L39
=> documenting cfn submit --set-default

src/rpdk/core/project.py, tests/test_project.py
*Issue #, if available:* #670
*Description of changes:* Allows additional properties in settings so settings loading is forwards compatible. Added small modification to test to show how additional properties are handled.
=> Remove additional properties constraints

src/rpdk/core/__init__.py
*Description of changes:* Bump the version to release cli
=> Bump version to 0.2.2

src/rpdk/core/__init__.py
*Description of changes:* bump version to 0.2.3
=> bump version 0.2.3

.gitignore
*Description of changes:* schema.json file should be ignored
=> Ignore schema.json file

src/rpdk/core/__init__.py
*Description of changes:* Bump version to release cli
=> Bump version

src/rpdk/core/project.py
Issue #640
When we validate the fragments folder we only look at files ending on json or yaml, but when we run cfn submit we just zip up everything in the fragments folder. This can cause the module registration to fail when there are unrelated files in that folder (such as files created by an IDE for example). This PR changes the file-zipping logic to only include the relevant fragment files.
I tested this by running `cfn init -a m -t Malik::extra::file::MODULE` and then creating an arbitrary txt file in the fragments folder.
This is the output of cfn submit before and after this change
**Before**
```
Failed to register the type with registration token '...'.
Please see response for additional information: '{'ProgressStatus': 'FAILED', 'Description': 'Deployment …
```
=> Issue 640 Ignore unrelated files when creating modules zip

src/rpdk/core/__init__.py
Bumping the version number so we can release the latest changes
Issues #640 #689 #693 
=> Bump version 0.2.5 -> 0.2.6

requirements.txt
*Description of changes:* Update pylint to the latest version
*Test: *
```
(env) 3c22fbb25c23:cloudformation-cli anshikg$ pre-commit run --all-files
seed isort known_third_party.............................................Passed
isort....................................................................Passed
black....................................................................Passed
Check for case conflicts.................................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
Trim Trailing Whitespace.................................................Passed
Flake8............................................................ …
```
=> Update the version for pylint

src/rpdk/core/__init__.py
*Description of changes:* Bump version
=> Bump version 0.2.7

.gitignore, README.md
These steps are necessary to successfully run all unit tests, so they should be mentioned in the readme
=> Update Readme with npm and jsonata steps

.github/workflows/contract-integration.yaml
[Installing the AWS SAM CLI on Linux](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html)
[Testing resource types using contract tests](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-test.html)
[`Encrypted secrets`](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets) for IAM actions currently required for resource ([`AWS::LookoutVision::Project`](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-lookoutvision/blob/main/aws-lookoutvision-project/aws-lookoutvision-project.json)) ([set here](https://github.com/aws-cloudformation/cloudformation-cli/settings/secrets/actions))
=> contract test integration test

src/rpdk/core/fragment/generator.py, src/rpdk/core/project.py, tests/test_project.py
Improving readability by breaking up some big functions. There are no functional changes here.
=> Improve readability by breaking up some big functions

.github/workflows/schema-updater.yaml
https://github.com/peter-evans/create-pull-request/issues/48
(initially set up in https://github.com/aws-cloudformation/cloudformation-cli/pull/647)
=> document Github Action workaround

.github/workflows/contract-integration.yaml
expanding test beyond only [Java resource provider](https://github.com/aws-cloudformation/cloudformation-cli/pull/714) using [`AWS::FraudDetector::Outcome`](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-frauddetector/blob/master/aws-frauddetector-outcome/aws-frauddetector-outcome.json)
=> contract test integration test (Python resource provider)

README.md, src/rpdk/core/cli.py, src/rpdk/core/contract/resource_client.py, src/rpdk/core/contract/suite/handler_commons.py, src/rpdk/core/contract/templates/transformation.template, src/rpdk/core/init.py, src/rpdk/core/jsonutils/flattener.py, src/rpdk/core/jsonutils/utils.py, src/rpdk/core/upload.py, tests/contract/test_resource_client.py
Removing npm dependency in cloudformation-cli
*Test:* 
* Ran contract test locally for a resource without property Transform:
```
platform darwin -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /Users/anshikg/workspace/cloudformation-cli/env/bin/python3
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/anshikg/workspace/aws …
```
=> Revert npm dependency

src/rpdk/core/__init__.py
*Description of changes:* Bumping the version to 0.2.8
=> Bump version 0.2.8

src/rpdk/core/project.py
*Description of changes:* Support for Node.js 14.x runtime
=> Support for Node.js 14.x runtime

setup.py
fixes https://github.com/aws-cloudformation/cloudformation-cli/issues/757
fixes https://github.com/aws-cloudformation/cloudformation-cli/issues/758
https://github.com/pallets/jinja/releases
=> pinning Jinja2 dependency

src/rpdk/core/__init__.py
to release https://github.com/aws-cloudformation/cloudformation-cli/pull/762
=> Bump version 0.2.10

src/rpdk/core/__init__.py
*Description of changes:* Bump version to 0.2.11
=> Bump version 0.2.11

src/rpdk/core/__init__.py
*Description of changes:* bump version 0.2.12
=> Bump version 0.2.12

.github/workflows/contract-integration.yaml
https://github.com/aws-cloudformation/cloudformation-cli/pull/714, https://github.com/aws-cloudformation/cloudformation-cli/pull/723
[`Found preexisting AWS SAM CLI installation: /usr/local/aws-sam-cli/current. Please rerun install script with --update flag.`](https://github.com/aws-cloudformation/cloudformation-cli/runs/2687615219#step:6:128)
=> sam-install --update in contract test integration test

src/rpdk/core/contract/interface.py, src/rpdk/core/contract/resource_client.py, tests/contract/test_resource_client.py
*Description of changes:* This CR ensures contract test fail if a resource doe snot have Create/Delete/Read handler as they are required handlers
*Test:* Ran contract test for a resource which does not have a read handler
```
========================================================================================================================================================================================================================================= test session starts =========================================================================================================================================================================================================================================
platform darwin -- Python 3.8.9, pytest-6.2.3, py-1.9.0, …
```
=> Fail Contract test if the required handlers are not present

src/rpdk/core/__init__.py
*Description of changes:* Bump version to 0.2.13
=> Bump version to 0.2.13

requirements.txt, src/rpdk/core/__init__.py
Bump cli version
Pin pylint version
=> Bump cli version and fix pylint exceptions

src/rpdk/core/contract/resource_client.py
*Description of changes:* Increase timeout for the session to avoid contract test failure
=> Increase botocore session to 15 mins

src/rpdk/core/__init__.py
*Description of changes:* Bumping the version to release the cli
=> Bump version to 0.2.15

src/rpdk/core/__init__.py
*Description of changes:* Bumping the version to release the cli
=> Bump version to 0.2.16

src/rpdk/core/boto_helpers.py, tests/test_boto_helpers.py
This reverts commit 866db5a73df2ff671f205126fc1d3c401792b1a5.
=> Revert "Increase Boto assumeRole duration to 6 hours (#814)"

src/rpdk/core/__init__.py
=> Bump version to 0.2.17

src/rpdk/core/__init__.py
=> Bump version to 0.2.18

src/rpdk/core/__init__.py
=> Bump version to 0.2.19

src/rpdk/core/data_loaders.py
Change warning for taggable to tagging
=> Change warning for taggable to tagging

src/rpdk/core/__init__.py
Issue #, if available:
Description of changes:
Bump version for release.
=> Bump version to 0.2.21

src/rpdk/core/contract/resource_client.py, src/rpdk/core/jsonutils/utils.py, tests/contract/test_resource_client.py
*Issue #, if available:* Closes #842
added a check for the last step during the traversal to prevent going deeper in levels
=> (Issue: #842) Added a check to prevent deeper traversal

src/rpdk/core/__init__.py
Bumping version to cut a release.
New Changes:
- #847
=> Bump version to 0.2.22

src/rpdk/core/data/managed-upload-infrastructure.yaml
* Add UpdateReplacePolicy for managed-upload-infrastructure.yaml
* Add dummy resource to trigger stack update
* simply adding the replace policy will not trigger a update
=> Add UpdateReplacePolicy for managed-upload-infrastructure.yaml

setup.py
*Issue #, if available:* https://github.com/aws-cloudformation/cloudformation-cli/issues/864
pinning jinja2 version and adding supporting lib
associated jinja issue - https://github.com/pallets/jinja/issues/1585
=> pin jinja version

src/rpdk/core/__init__.py
version bump to release jinja dependency fix
=> version bump v0.2.24

.pre-commit-config.yaml, src/rpdk/core/__init__.py
version bump to release hook fixes
=> version bump v0.2.25

.coveragerc, .pre-commit-config.yaml
- Pin importlib-metadata for bandit tests  https://github.com/PyCQA/bandit/issues/956
=> fix(test) - Pin importlib-metadata for bandit tests

tests/test_project.py
- Removes the dependency on `~/.aws/config` and having credentials
=> fix(test) - Remove dependency on ~/.aws/config and credentials

doc_source/modules-structure.md
*Description of changes:* documentation:
- Broken links
- Typo
=> Doc: Fix broken links and typo in  modules-structure.md

src/rpdk/core/templates/docs-readme.md, tests/data/schema/target_output/multiref.md
This is to fix the failing tests for PR #885
=> chore(documentation): fix tests for pr#885

.github/workflows/contract-integration.yaml, .github/workflows/pr-ci.yaml, .github/workflows/pypi-release.yaml, .github/workflows/schema-updater.yaml
Run tests on all branches/PRs
Update github actions to latest available
=> chore(CI): Update github actions to latest versions

src/rpdk/core/project.py, src/rpdk/core/templates/docs-readme.md, src/rpdk/core/templates/docs-subproperty.md, tests/data/schema/valid/valid_type_complex.json
https://github.com/aws-cloudformation/cloudformation-cli/pull/367#discussion_r395955803
https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/pull/121
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-some-interrupt
=> `generate_docs()` for conditionalCreateOnlyProperties

src/rpdk/core/__init__.py
=> version bump v0.2.27

src/rpdk/core/boto_helpers.py, src/rpdk/core/contract/hook_client.py, src/rpdk/core/contract/resource_client.py, src/rpdk/core/test.py, tests/test_boto_helpers.py, tests/test_test.py
- Convert headers to be a NamedDict for readability 
=> chore(test) - Convert headers to NamedDict

setup.py
- Update `Werkzeug` to at least `2.2.0`
=> update Werkzeug to 2.2.0

setup.py
Update `Jinja` and `markupsafe` for `soft_unicode` failure
=> Update Jinja and markupsafe for soft_unicode failure

src/rpdk/core/__init__.py
Bumping version to merge latest fixes
=> Bump version to 0.2.29

src/rpdk/core/data/managed-upload-infrastructure.yaml
Removing condition on Source Account to enable Handler Log Delivery.
=> Remove sourceAccount condition from logsAndMetrics delivery role

setup.py, src/rpdk/core/__init__.py, src/rpdk/core/data/managed-upload-infrastructure.yaml
https://github.com/aws-cloudformation/cloudformation-cli/pull/988
=> Bug fixes and bumping version

src/rpdk/core/__init__.py
=> Bump version to 0.2.31

src/rpdk/core/contract/resource_client.py, src/rpdk/core/data/schema/provider.definition.schema.v1.json, tests/contract/test_resource_client.py
Update tagging schema with permissions field.
Add unit test for tagging permissions field.
=> Add permissions to tagging schema

src/rpdk/core/__init__.py
Bump version to 0.2.32 to release tagging schema changes
=> Bump version to 0.2.32

setup.py
- Because of cython>3 release we need to update PyYaml
=> Because of cython>3 release we need to update PyYaml

src/rpdk/core/__init__.py
=> Version bump

.github/workflows/pr-ci.yaml, setup.py
- Add support up to python 3.11
=> Add support up to python 3.11

src/rpdk/core/__init__.py
=> bump version to 0.2.34

src/rpdk/core/__init__.py
=> Version Bump: 0.2.35

src/rpdk/core/__init__.py
=> Version Bump: 0.2.36

src/rpdk/core/__init__.py
- Bump for Version 0.2.38
- Releasing canary autogeneration for update canaries: https://github.com/aws-cloudformation/cloudformation-cli/pull/1074
- Releasing logging for canary auto-generation and semantic changes for canarySettings: https://github.com/aws-cloudformation/cloudformation-cli/pull/1078
=> Release for Version 0.2.38

src/rpdk/core/boto_helpers.py
=> Remove confused deputy logs

src/rpdk/core/__init__.py
*Description of changes:* Bump version to 0.2.39 for new cli version release
=> Release for Version 0.2.39
