- setup.py
- src/rpdk/core/__init__.py
- src/rpdk/core/project.py
- tests/test_project.py
*Description of changes:* Just realized that to get a waiter, you have to use snake case for the waiter name instead of camel case. Tested locally.
> Use waiter defined in SDK

- examples/schema/aws.common.types.v1.json
https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-arns.html
We should also consider something more general like:
`arn:aws(-[a-z-]*)?:`
> fixing GovCloud arn partition

- src/rpdk/core/init.py
- src/rpdk/core/plugin_registry.py
- src/rpdk/core/project.py
- tests/test_init.py
*Description of changes:* With CI that can run against different langauge versions, it will be more important to be able to accurately select the language version. The current approach of echoing the choice is a bit brittle.
```bash
$ cfn init --language "python37"
Initializing new project
What's the name of your resource type?
(Organization::Service::Resource)
>> AWS::Foo::Bar
Language plugin 'python37' selected non-interactively
```
This change also ensures plugin choice list is deterministically sorted and updates some Lambda runtimes.
> Non-interactively select language plugin for CI

- README.rst
*Description of changes:* A cell's contents in a table in rst needs to be in the span of the columns. The naming change in #359 moved this around and caused the table to not render. Display the "Source Diff" to see the addition of the table
> Fix spacing on plugin table

- src/rpdk/core/data/managed-upload-infrastructure.yaml
- src/rpdk/core/data/schema/provider.definition.schema.v1.json
- src/rpdk/core/project.py
- src/rpdk/core/templates/resource-role.yml
- tests/test_project.py
This increases the managed provider IAM role to 12 hours, and generates a value for the resource provider role timeout based on the max handler timeout.  This allows for timeouts up to 12 hours
Related: https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/pull/61
> increase IAM role max session timeouts to support custom stabilization up to 12 hours

- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/contract/suite/handler_delete.py
- tests/contract/test_resource_client.py
*Description of changes:* Contract tests for certain providers were failing the delete_create duplicate test. It turns out the prune_properties function used to try to remove the readOnly properties from both the deleted model and the newly created model wasn't actually pruning anything because the paths included the "/properties" prefix. This adds a function for pruning models (that do not have a "properties" key) and uses that function in the contract test. 
The test is also skipped if the schema does not contain any writable identifiers/
> Add resource model pruning function and fix contract test

- src/rpdk/core/data/schema/provider.definition.schema.v1.json
- src/rpdk/core/data_loaders.py
- tests/test_data_loaders.py
*Issue #, if available:* Please see #344 , which hasn't fared too well due to the rename.
*Description of changes:* Now that `$id` is allowed in schemas, make use of it. This will make testing `$ref` to other schemas easier, as they don't need to be present on the local filesystem.
> Use $id if defined in schema

- requirements.txt
- setup.py
- src/rpdk/core/plugin_base.py
- tests/test_plugin_base.py
*Issue #, if available:* 387
*Description of changes:* Work around update to Jinja2 that breaks pytest's mangling of module loaders.
> Use PEP451 loader to work around pytest/jinja2 disagreements (#387)

- src/rpdk/core/project.py
- tests/test_project.py
*Issue #, if available:* N#A
*Description of changes:* Allows plugins to call `write_settings` on the project. We need this in the Go plugin as we're intending to store plugin version information in `.rpdk-config`. See https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/pull/115
> Allow external use of write_settings

- src/rpdk/core/data/managed-upload-infrastructure.yaml
*Description of changes:* For security reasons;
- Created new bucket `AccessLogsBucket` to store s3 server access logs of `ArtifactBucket`
- Enabled versioning in both buckets (`ArtifactBucket` and `AccessLogsBucket`)
- Set `LifecycleConfiguration` to maximum value
> Enable versioning and server access logging for ArtifactBucket

- .travis.yml
- requirements.txt
*Description of changes:* The [`twine check`](https://github.com/pypa/twine/#twine-check)  command verifies that a distribution could be uploaded to PyPI. This will ensure that  generated distributions can be uploaded to PyPI.
> Verify packaging in CI

- src/rpdk/core/test.py
- tests/test_test.py
The CloudFormation CLI performs resource contract tests using input that is generated from the patterns you define in your resource's property definitions. However, some inputs can't be randomly generated. For example, the AWS::EC2::Instance SubnetId property requires an actual subnet ID for testing, not just a string that matches the appearance of a subnet ID. So in order to test this property, we need to include a file with actual values for the contract tests to use. The file would currently look like this:
```
{
"CREATE": {
"/SubnetId": "subnet-0bc6136e" 
}
}
```
It would be useful if instead of hardcoding the values, we could reference CloudFormation exports. That way you could create the resource dependencies through a CloudFormation stack and reference them easily in the overrides …
> Support CloudFormation exports for dynamic values in overrides file

- src/rpdk/core/project.py
- tests/data/schema/valid/valid_no_type.json
- tests/test_project.py
*Description of changes:* `type` is not a required key when declaring a definition/property. When auto-generating the docs, it assumed that `type` would always be specified. This sets the type to object if it is not specified in the schema which is the default.
Tested with a unit test and a personal type. 
> Set default type when generating docs to object

- src/rpdk/core/project.py
*Description of changes:* Allows plugins to initialize project with settings object. This is needed to inject settings directly for the unit tests in the Typescript plugin instead of having to modify generated files. Please, refer to this related code in Typescript plugin repo: https://github.com/eduardomourar/cloudformation-cli-typescript-plugin/blob/0b534882fd961062d47e62f9278d20b5e46a3395/tests/plugin/codegen_test.py#L40-L43
> Add settings parameter to project init

- .pre-commit-config.yaml
- setup.cfg
*Description of changes:*. isort is broken, and it also [conflict with blank](https://github.com/psf/black/issues/251).
Also the PR #436  fails on isort without change of those files because of it.
It's recommended to use [seed-isort-config](https://github.com/asottile/seed-isort-config) to populate the known_third_party isort setting. 
After that, my local command `pre-commit run --all-files` works well.
> Use seed-isort-config for isort dependencies

- setup.cfg
- src/rpdk/core/data/schema/meta-schema.json
- src/rpdk/core/data_loaders.py
- tests/test_data_loaders.py
*Issue #, if available:* #228 
*Description of changes:*.  Currently `cfn generate` will do schema validation, and therefore it will require network to get the meta schema reference from internet `https://json-schema.org/draft-07/schema`.
This PR get the meta schema from `https://json-schema.org/draft-07/schema` and store with the resource schema, therefore, it will resolve it from local file instead from internet.
Also it provides a better meta schema locking as we source control the meta schema now.
> Use local meta schema for reference to support disconnected network build

- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/contract/suite/handler_commons.py
- src/rpdk/core/contract/suite/handler_create.py
- src/rpdk/core/contract/suite/handler_delete.py
- src/rpdk/core/contract/suite/handler_update.py
- src/rpdk/core/jsonutils/pointer.py
- tests/contract/test_resource_client.py
*Description of changes:* Following are changes made in this PR:
1. Check if Primary Identifier is added after create finishes successfully
~~2. Check  Primary Identifier should not exist after unsuccessful create finishes~~
3. Check Primary Identifier after update has not changed.
4. Assert ResourceModel does not exist  in response after delete.
5. Test case where update fails with NotUpdatable error code when, we try to update an existing resource with readOnly/createOnly property
6. Test case where update fails with NotFound error code when the resource does not exists.
7. Check if Primary Identifier is added after in_progress is returned.
*Test*:
1. **pre-commit run --all-files**  to build the contract test changes
2. **cfn test** to run the contract test for …
> Desired state stabilization contract test

- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/contract/suite/handler_commons.py
- tests/contract/test_resource_client.py
*Issue #, if available:* https://github.com/aws-cloudformation/cloudformation-cli/pull/450/
~~1)  verify "In Progress event" is being returned. If so, verify the resource created and the model returned have the same set of values~~
2) Verify "WriteOnlyProperties" are not being returned.
*Test*
```
(env) 88e9fe53273b:aws-ses-configurationset anshikg$ cfn test
=========================================================================================== test session starts ============================================================================================
platform darwin -- Python 3.7.2, pytest-5.4.2, py-1.8.1, pluggy-0.13.1 -- /Volumes/Unix/workspace/rpdk/cloudformation-cli/env/bin/python3
hypothesis profile 'default' -> …
```
> Shape Conformance Contract test

- src/rpdk/core/contract/resource_client.py
- tests/contract/test_resource_client.py
Contract test assert when handler return Callback context on fail/success handlers. This seems unnecessary. Removing this check from the contract test
> Remove Callback Context assert for handler success and failure

- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/project.py
- src/rpdk/core/test.py
- tests/contract/test_resource_client.py
- tests/test_project.py
- tests/test_test.py
*Description of changes:* This CR will allow customers to enter their own input to the Contract test suite. This will be advantageous for resources with complex inputs. 
In this case user can add a file under root/inputs/ the expected name format is inputs_1_create.json
User can enter create file with postfix: _create.json
User can enter update file with postfix: _update.json
User can enter invalid file with postfix: _invalid.json
Users can enter multiple input files. inputs_1, inputs_2, inputs_3 these 3 will be treated at 3 separate inputs from the user.
*Testing:* 
- used cfn submit to check if the inputs folder was created in the zip file
- build the cfn package: **pre-commit run --all-files**
- ses configurationset: ** cfn test**
```
(env) …
```
> Allow Customers to add Input to Contract test

- src/rpdk/core/jsonutils/resolver.py
- src/rpdk/core/project.py
- tests/data/schema/valid/valid_pattern_properties.json
- tests/jsonutils/test_resolver.py
added a generic type for multi type support. 
Example:
```json
"property1": {
"type": ["string", "object"]
}
}
```
generated `ResourceModel.java`:
```java
@JsonAutoDetect(fieldVisibility = Visibility.ANY, getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE)
public class ResourceModel {
@JsonProperty("property1")
private Object property1;
...
```
test cases:
* 1  [CREATE] with escaped string `property1` -> [UPDATE] with modified escaped string `property1`
* 2 [CREATE] with escaped string `property1` -> [UPDATE] with json object `property1` 
* 3 [CREATE] with json object `property1` -> [UPDATE] with modified json `property1`
* 4 [CREATE] with list input for `property1` -> Failed with error `Model …
> added generic  type for multiple type support

- src/rpdk/core/boto_helpers.py
- tests/test_boto_helpers.py
*Description of changes:* The [AWS recommendation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html) is to use regional sts endpoints when we are assuming roles. When an sts client is generated with boto3, the global endpoint is used. This PR generates the sts service endpoint and uses that when creating the client instead of the global endpoint. 
boto3 does not support an option to use the regional endpoint so we need to generate it ourselves: https://github.com/boto/boto3/issues/1939
This was tested with unit tests. I also tested manually by running cfn test with a role arn with a personal resource along with just running cfn test without a role arn
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> Use regional sts endpoints

- src/rpdk/core/contract/resource_client.py
*Description of changes:* It seems contract test expect Create, Update and Delete handlers to complete in 60 seconds. This is not possible for most resources. Therefore, changing the handler assert to assert when a Progress Event is returned. This includes Success, Failure and InProgress. This also in aligned with the handler contracts: 
```
A create handler MUST always return a ProgressEvent object within 60 seconds. For more information, see ProgressEvent Object Schema.
```
> Assert CRUDL timeout for all Progress Events

- src/rpdk/core/contract/suite/handler_commons.py
*Issue #, if available:* https://github.com/aws-cloudformation/cloudformation-cli/issues/462
*Description of changes:* This change ensures the assert for primary identifier and writeOnly property is made on returned resourceModel
*Test:*
1. pre-commit run --all-files
2. cfn test for ses-configurationset
```
======================================================================================= test session starts anshikg ========================================================================================
platform darwin -- Python 3.7.2, pytest-5.4.2, py-1.8.1, pluggy-0.13.1 -- /Volumes/Unix/workspace/rpdk/cloudformation-cli/env/bin/python3
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Volumes/Unix/workspace/aws-cloudformation-resource- …
```
> Assert on created/updated model

- README.md
n/a
Add the CloudFormation CLI Python Plugin PyPI link now that it is published as v2.0.0.
> Add CFN CLI Py Plugin PyPI Link

- src/rpdk/core/contract/suite/handler_update.py
*Issue #, if available:* #426 
*Description of changes:* This fixes the update fixture used in contract tests to be in line with how the create fixture operates:
https://github.com/aws-cloudformation/cloudformation-cli/blob/dbf6dc34f1ee52b9baf6d0a78b1e62e7f06f83d7/src/rpdk/core/contract/suite/handler_create.py#L23-L31
> Fix update contract test fixture

- src/rpdk/core/contract/resource_client.py
- tests/contract/test_resource_client.py
*Description of changes:* Contract test was asserting that writeOnlyProperties are not returned on an IN_PROGRESS result which is problematic, as many resources need writeOnlyProperties to exist on the resource through re-invocation or stabilization checks. The redaction assert is only needed on the final result from a SUCCESS or FAILED response.
> Fixed contract test check on writeOnlyProperties redaction

- src/rpdk/core/project.py
- tests/data/schema/target_output/multityped.md
- tests/data/schema/valid/valid_multityped_property.json
- tests/data/schema/valid/valid_type_complex.json
- tests/test_project.py
enhanced docgen for multityped properties:
* using flattened schema to generalize [`allOf`, `anyOf`, `oneOf`]
e.g
following structure:
```
{
...
"Property1": {
"oneOf": [
{
"type": "string"
},
{
"type": "object"
},
{
"type": "boolean"
},
{
"type": "array",
"items": {
"$ref": "#/definitions/CustomObject"
}
}
]
}
}
}
```
will result in:
```md
{
"Type" : "AMZN::SAMPLE::RESOURCE",
"Properties" : {
...
"Property1" : String, Map, Boolean, [ CustomObject, ... ],
}
}
```
------------------------
* `propname` and `proppath` are tied to the `$ref` type, which helps now use the correct name
e.g.
following structure:
```json
{
...
"definitions": {
"Tag": { ... }
},
...
"Tags": {
"type": "array",
"items": {
"$ref": …
```
> added docgen for multi typed properties

- src/rpdk/core/contract/resource_client.py
- tests/contract/test_resource_client.py
Removed an assert requiring that ProgressEvent results with a status of FAILED should not include a ResourceModel.
This requirement is not actually part of the handler contract: https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-test-contract.html and was likely added to ensure consistency on this result as the model is strictly ignored in this case.
However, given this is not a documented part of the contract and there are no adverse outcomes from including a model in FAILED events, the test is an impediment and not a protection.
> Removed empty model assert in contract tests

- src/rpdk/core/contract/suite/handler_read.py
- src/rpdk/core/contract/suite/handler_update.py
*Issue #, if available:*https://github.com/aws-cloudformation/cloudformation-cli/issues/494
* Adding a test case to check if read fails when no resource was created.
* **contract_update_create_only_property**  fails with Not_Found error code in resources where createOnly property is also the primary Identifier. Therefore asserting for either error codes.
> Add read without create test, add error code to update handler

- src/rpdk/core/contract/suite/handler_update.py
- src/rpdk/core/contract/suite/handler_update_invalid.py
*Issue #, if available:* https://github.com/aws-cloudformation/cloudformation-cli/issues/488
fixtures for update handler test need to run for functions which need the create and update common model/request
* Test:*
* Ran test for elasticloadbalancing::loadbalancer
```
platform darwin -- Python 3.8.4, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /Users/anshikg/workspace/cloudformation-cli/env/bin/python3
Test order randomisation NOT enabled. Enable with --random-order or …
```
> Fix the fixture scope for update handler

- src/rpdk/core/contract/suite/handler_commons.py
this is also a part of this issue #361
We need to assert that primary id did not get changed withing handler code
> asserts that primary id has not got changed throughout update

- src/rpdk/core/jsonutils/resolver.py
- src/rpdk/core/project.py
- tests/data/schema/valid/valid_multityped_property.json
- tests/jsonutils/test_resolver.py
- tests/test_project.py
added a check to avoid setting property to `Object` if it has conditional subschema with the same type as flattened type would be `type: [string, string]`;
Example:
```json
{
"SampleObject": {
"type": "object",
"oneOf": [
{
"properties": { "Type": { "type": "string" } }
},
{
"properties": { "Type": { "type": "string" } }
}
]
}
}
```
> removed potential duplicate types within array

- src/rpdk/core/boto_helpers.py
- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/contract/suite/handler_delete.py
- tests/contract/test_resource_client.py
- tests/test_boto_helpers.py
*Issue #, if available:* https://github.com/aws-cloudformation/cloudformation-cli/issues/501
*Description of changes:* Contract test does not provide a mechanism to add Region/Partition/AccountId to the contract test request. This change will allow users to add the above mentioned values as parameters.
*Test:* Ran the following command successfully:
```
(env) anshikg@3c22fbb25c23 aws-elasticloadbalancing-loadbalancer % cfn test --region "us-west-2" --partition "aws" --account-id "12345678" -- -k contract_create_delete
platform darwin -- …
```
> Add region, partition and accountId to contract test request to handler

- src/rpdk/core/contract/suite/contract_asserts.py
- src/rpdk/core/contract/suite/handler_commons.py
- src/rpdk/core/contract/suite/handler_create.py
- src/rpdk/core/contract/suite/handler_update.py
- src/rpdk/core/contract/suite/handler_update_invalid.py
adding a module where we could concentrate all the checks or asserts necessary for tests cases and decorate them.
It has a parent method `decorate` which makes decorator out of any simple function. The convention is to have variables that could be either returned by the target function (which is `response` if not returned then `None`) or accepted by the target function (e.g. `resource_client`). `decorate` rebinds `positional` or `keyword_or_positional` args from the target function and rebinds it to the assumed decorator. 
Then it could be used to decorate any method, which response needs to be checked upon `write_only_properties` or something else
By submitting this pull request, I confirm that my contribution is made under the terms of …
> added asserts into a library

- requirements.txt
- src/rpdk/core/templates/template.yml
*Issue #, if available:* #510 
increasing the default memory size
bumping pytest to 6.x as annotations were not recognized as callable  https://github.com/pytest-dev/pytest/issues/7473
> increasing default lambda memory size

- src/rpdk/core/data/pytest-contract.ini
The following warning is generated when running `cfn test`:
```
================================================================= warnings summary ==================================================================
.venv/lib/python3.7/site-packages/_pytest/logging.py:499
.venv/lib/python3.7/site-packages/_pytest/logging.py:499: PytestDeprecationWarning: --no-print-logs is deprecated and scheduled for removal in pytest 6.0.
Please use --show-capture instead.
_issue_warning_captured(NO_PRINT_LOGS, self._config.hook, stacklevel=2)
```
Migrate to new pytest option to resolve warning.
> Update pytest log printing option

- src/rpdk/core/contract/suite/handler_create.py
*Issue #, if available:*https://github.com/aws-cloudformation/cloudformation-cli/issues/517
*Description of changes:* Adding a delete call to delete partially created resources.
> Delete partial resource created by invalid create test

- src/rpdk/core/contract/suite/contract_asserts.py
- src/rpdk/core/contract/suite/handler_commons.py
- src/rpdk/core/contract/suite/handler_create.py
- src/rpdk/core/contract/suite/handler_read.py
- src/rpdk/core/contract/suite/handler_update_invalid.py
*Issue #, if available:* #507 
**contract_read_without_create**
Test anticipates `NotFound` error as it invokes `ReadHandler` without prior creation of the resource. This test starts with `resource_client.generate_create_example` but it's pretty hard to provide a good generation strategy for primary identifier to mock a good value, as primary identifier pattern is not always good enough to generate a good substitute (e.g. `arn` - partition or region constraints). This test might be very inconsistent if we rely on generation strategy, as different api might throw different error - `NotFound`, `InvalidRequest`, `CfnGeneralException`, etc. 
Eventually, this test checks if `ReadHandler` throws `NotFound` exception in case the resource has already been deleted. This …
> added a writable id skip for read without create

- src/rpdk/core/project.py
- tests/data/schema/target_output/multityped.md
@iann0036 https://github.com/aws-cloudformation/cloudformation-cli/pull/367/files#r465968007
["In my JSON schema I clearly define one of my properties to be a “type”: “integer”, yet no matter what when run mvn package, it will always generate docs/README.md with incorrect JSON/YAML type specifying the property to Double instead of Integer. I have no idea why it is changing my desiredInferenceUnits property expect a Double and would appreciate anyone who knows how to fix the way the docs/README.md is generated. I have attached a picture of the incorrectly generated doc below."](https://list-archive.amazon.com/lists/1110/messages/10489862)
---
Most common `PrimitiveType` values in the [Resource Specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specifi …
> mapping integer to Integer instead of Double in generated documentation

- src/rpdk/core/contract/resource_client.py
I dont think we need to assert for write only properties on anything but successful event. especially with call chain it becomes hard to maintain as resource model is carried over to each method and is not considered to be changed as it will change the hashcode for the call graph
> added assert only on successful event

- src/rpdk/core/contract/resource_client.py
`rpdk.log` output snippet from testing locally with `pip install -e .`:
```
[2020-08-11T02:28:40Z] DEBUG    - Sending request
{
"callbackContext": null,
"action": "CREATE",
"request": {
"clientRequestToken": "e22a98c1-3dd6-4d47-840d-b3fedd7811f2",
"desiredResourceState": {
"Name": "񺈈",
"OperatingSystem": "AMAZON_LINUX",
"StorageLocation": {
"Bucket": "cf-templates-1nku2armaeosd-us-east-1",
"Key": "gamelift.zip",
"RoleArn": "arn:aws:iam::591441109405:role/GameLiftBuildRole-Role-ULTQ2VWEFA2B"
},
"Version": "+ "
},
"previousResourceState": null,
"logicalResourceIdentifier": null,
"region": "us-east-1",
"awsPartition": "aws",
"awsAccountId": "591441109405"
}
}
```
> reducing logging output

- src/rpdk/core/contract/suite/contract_asserts.py
- src/rpdk/core/contract/suite/handler_update_invalid.py
*Description of changes:* Contract test which have just one create only property as identifier fail with NotFound error code instead of NotUpdatable
*Test*
* Ran the test against cloudwatch alarm resource
> Fix Contract test for resources with one createOnly Property

- src/rpdk/core/data/schema/provider.definition.schema.v1.json
the timeout limit has increased from 12 hrs to 36 hrs. Hence, we also need to increase timeoutInMinutes from 720 to 2160 (36 x 60)
> Increase timeoutInMinute to 2160

- src/rpdk/core/contract/suite/handler_delete.py
*Issue #, if available:* https://github.com/aws-cloudformation/cloudformation-cli/issues/524
*Description of changes:* Resources which have readonly identifiers are unable to be deleted because the read only identifier is not present in the fixture.
> Delete the resource in contract_delete_create test

- .pre-commit-config.yaml
- src/rpdk/core/project.py
- src/rpdk/core/templates/inputs.json
- tests/test_project.py
added `inputs`/{`inputs_1_create.json`, `inputs_1_update.json`, `inputs_1_invalid.json`} on `cfn init`
> added inputs generation on [cfn init]

- src/rpdk/core/boto_helpers.py
- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/contract/suite/handler_commons.py
- src/rpdk/core/contract/suite/handler_delete.py
- src/rpdk/core/contract/suite/handler_update_invalid.py
- src/rpdk/core/jsonutils/pointer.py
- src/rpdk/core/test.py
- tests/contract/test_resource_client.py
- tests/test_boto_helpers.py
- tests/test_invoke.py
- tests/test_test.py
*Issue #, if available:* https://github.com/aws-cloudformation/cloudformation-cli/issues/544
*Description of changes:* This PR changes the contract tests so that they will use the role credentials if a role is passed in when constructing clients. This also introduces using the regional sts endpoint when constructing the sts client when we get the account id
My testing setup was to have one account's credentials exported locally but then pass in another account's role-arn when running cfn test. Tested with and without the role-arn to ensure the account id was correct and the overrides were picked up as expected (not found when using the local credentials and found when using the role-arn) from the stack exports.   
By submitting this pull request, I confirm that my contribution is made …
> Use role credentials when constructing clients for contract tests and use regional sts endpoint when getting account id

- .pre-commit-config.yaml
- README.md
- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/contract/suite/contract_asserts.py
- src/rpdk/core/contract/suite/handler_commons.py
- src/rpdk/core/contract/suite/handler_delete.py
- src/rpdk/core/contract/suite/handler_update.py
- src/rpdk/core/contract/suite/handler_update_invalid.py
- src/rpdk/core/data/pytest-contract.ini
- tests/contract/test_resource_client.py
added messages to all assertions so it will be clear why certain test failed;
removed the full stack trace to a `short` option as it outputs the assertion message and method it comes from; 
> adjusted summary report

- src/rpdk/core/__init__.py
- src/rpdk/core/contract/resource_client.py
- tests/contract/test_resource_client.py
*Issue #, if available:* https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/issues/112 https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/issues/109
*Description of changes:* The request to the resource handlers for contract tests is slightly wrong in structure, causing hard failures while testing via the python plugin (partition isn't a field in the [request](https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/blob/master/src/cloudformation_cli_python_lib/utils.py#L83-L95)).
This should fix the request. Tested with the python plugin and tests ran succesfully with some other changes to the lib that will go out after this. Also bumping the version to expedite a release.
By submitting this pull request, I confirm that my …
> Restructure request to match handlers

- src/rpdk/core/contract/resource_client.py
- tests/contract/test_resource_client.py
*Issue #, if available:* #506 
adding `try-catch/except` handling on json decoder runtime issues; 
> adding json decoding runtime error handling

- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/contract/suite/contract_asserts.py
- src/rpdk/core/contract/suite/handler_commons.py
- src/rpdk/core/contract/suite/handler_create.py
- src/rpdk/core/contract/suite/handler_delete.py
- src/rpdk/core/contract/suite/handler_update.py
- src/rpdk/core/contract/suite/handler_update_invalid.py
- tests/contract/test_resource_client.py
*Description of changes:* The current master branch is broken due to this change. This is because delete/read handlers are invoked using the primary identifier this causes the language specific validation to fail because we assert on this for Delete and read handler. For now this change needs to be reverted to reduce customer pain point. 
*Test*
```
========================================================= test session starts =========================================================
platform darwin -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /Users/anshikg/workspace/cloudformation-cli/env/bin/python3
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
hypothesis profile …
```
> Revert Delete & Read Handler should be invoked using identifiers (#537)

- src/rpdk/core/contract/suite/handler_create.py
- src/rpdk/core/contract/suite/handler_update.py
*Description of changes:* This ensures the input to create/update handler is equal to the output of read handler. This ensure the resource is not falsely drifted.
> Compared create/update input to read output

- .coveragerc
- src/rpdk/core/invoke.py
- tests/test_invoke.py
*Issue #, if available:*https://github.com/aws-cloudformation/cloudformation-cli/issues/594
* Updated the coverage to 100%
* Fixed the cfn invoke functionality
*Test:*
Ran cfn invoke
```
=== Handler input ===
{
"requestData": {
"callerCredentials": {
"accessKeyId": "",
"secretAccessKey": "",
"sessionToken": ""
},
"resourceProperties": {
"AlarmName": "TestAlarm1",
"AlarmDescription": "TestAlarmDimensions Description",
"Namespace": "CloudWatchNamespace",
"MetricName": "Fault",
"Statistic": "Average",
"Period": 60,
"EvaluationPeriods": 5,
"Threshold": 0.01,
"ComparisonOperator": "GreaterThanOrEqualToThreshold"
},
"previousResourceProperties": {
"AlarmName": "TestAlarm1",
"AlarmDescription": "TestAlarmDimensions Description",
"Namespace": "CloudWatchNamespace", …
```
> Fix cfn invoke with TypeFunction entry point

- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/contract/suite/contract_asserts.py
- src/rpdk/core/contract/suite/handler_delete.py
- tests/contract/test_resource_client.py
*Issue:* #585
The has_writable_identifier() is called during the execution of the contract_create_duplicate() test. 
- We only need to check primaryIdentifiers here, additionalIdentifiers  does not appear to be used. 
- Updated to check if all primaryIdentifiers are readOnly
> Fix writable identifier check for composite key primary identifier

- src/rpdk/core/data/managed-upload-infrastructure.yaml
*Description of changes:*. The `LogAndMetricsDeliveryRole` will only be assumed-role by `resources.cloudformation.amazonaws.com`. Remove unused service principal.
> Remove cloudformation.amazonaws.com Service principal

- src/rpdk/core/data_loaders.py
> fixed composite id validation

- src/rpdk/core/contract/suite/handler_update.py
If read only paths change with updates, contract tests fail because the readonly property value does not match the previous value.
This change prunes readonly paths from the input model so when comparing input model to output model, readonly paths are not considered.
*Issue #, if available:* [609](https://github.com/aws-cloudformation/cloudformation-cli/issues/609)
*Description of changes:* prune readonly paths from input model in `test_input_equals_output`, and update the message accordingly. 
> prune readonly paths from input model for test_input_equals_output

- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/contract/suite/handler_commons.py
- tests/contract/test_resource_client.py
*Issue #, if available:* https://github.com/aws-cloudformation/cloudformation-cli/issues/580
*Description of changes:* This CR has a change for insertionOrder metadata check. It is added to ensure drift parity. This metadata if set to false ensures order does not matters
*Test*
* unit test
* ran contract test
```
(env) 3c22fbb25c23:aws-cloudwatch-alarm anshikg$ cfn test --enforce-timeout 120
=================================================================================================================== test session starts ====================================================================================================================
platform darwin -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /Users/anshikg/workspace/cloudformation-cli/env/bin/python3
cachedir: …
```
> Add check for insertionOrder and unique for drift parity

- src/rpdk/core/data/schema/meta-schema.json
- src/rpdk/core/data/schema/provider.definition.schema.v1.json
*Description of changes:* Adding a property transform function to define what the read handler would return for created/updated property. This change is ensuring the cfn validate does not fail on propertyTransform.
*Test:*
* pre-commit run --all-files
* run ```cfn validate``` for a schema file with ```propertyTransform``` set.
> Add propertyTransform to transform the properties to expected output

- src/rpdk/core/plugin_registry.py
*Issue #, if available:* #616 
Multiple entries of the same language were being returned as a plugin choice. Use set() to return only unique choices
> Dedup plugin choices after fetching them from registry

- src/rpdk/core/contract/suite/handler_update.py
*Issue #, if available:* #624
we must clone before modifying the resource model read from output of create handler so that we are not incorrectly modifying the payload for update request. Previously the code was stripping readOnly properties from `update_request` payload. Due to this, update handler contract tests were failing for some resources.
> fix update handler bug

- src/rpdk/core/__init__.py
- src/rpdk/core/jsonutils/resolver.py
- tests/jsonutils/test_resolver.py
*Issue #, if available:*  https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/issues/151
*Description of changes:* This allows the [format keyword](https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/blob/master/src/main/resources/schema/provider.definition.schema.v1.json#L201-L203) to be passed to plugins to allow construction of types with specific format akin to the OpenAPI specification for certain primitives (thanks @bkabrda for the suggestion.) This is to be reviewed alongside this java plugin PR: https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/328
TL;DR (for specific https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/issues/151 issue):
Customers can now add format to their integer schemas to specify …
> Include format in ResolvedType

- src/rpdk/core/boto_helpers.py
- src/rpdk/core/contract/resource_client.py
- tests/contract/test_resource_client.py
- tests/test_boto_helpers.py
- tests/test_invoke.py
*Issue #, if available:*. N/A
There are 2 problems to fix here:
- Only create temporary credential once during the whole contract test is not right.  The resource stabilization could be more than default credential time 1 hour and it will fail. Also this doesn't match how cloudformation get temporary credential for each invocation.
- With above change, we can limit the credential to 15 mins to enhance the security.
Run contract test with log group. (some contract test failed with log group but it's not because of this change)
> Create temporary credential for each invocation and limit duration to 15 mins

- requirements.txt
- setup.cfg
- src/rpdk/core/jsonutils/flattener.py
- src/rpdk/core/jsonutils/utils.py
- src/rpdk/core/project.py
- tests/data/schema/target_output/multiref.md
- tests/data/schema/valid/valid_multiref_property.json
- tests/jsonutils/test_flattener.py
- tests/test_project.py
adding multi `$ref` support to enrich schema capabilities to support multiple types; 
usecases:
```json
{
"propertyA": {
"oneOf": [
{"$ref": "#..."},
{"$ref": "#..."},
{"type": "..."}
]
}
}
}
```
--------------------------------------
```json
{
"typeName": "AWS::Valid::TypeName",
"description": "a test schema",
"definitions": {
"ComplexTypeWithOnePrimitive": {
"type": "object",
"PrimitiveProperty": {
"type": "string"
}
}
},
"ComplexTypeWithMultiplePrimitives": {
"type": "object",
"PrimitiveProperty1": {
"type": "string"
},
"PrimitiveProperty2": {
"type": "string"
}
}
}
},
"primaryID": {
"type": "string"
},
"PropertyWithTwoComplexTypes": {
"oneOf": [
{
"$ref": …
```
> Multi Ref Support

- requirements.txt
- setup.py
- src/rpdk/core/__init__.py
*Description of changes:* Need to add the ordered_set dependency to the package dependencies and not the dev dependencies. 
On 0.2.0:
```
(env) jotompki@3c22fb7f6043 test-cli % cfn init
Traceback (most recent call last):
File "/Users/jotompki/test-cli/env/bin/cfn", line 5, in <module>
from rpdk.core.cli import main
File "/Users/jotompki/test-cli/env/lib/python3.9/site-packages/rpdk/core/cli.py", line 12, in <module>
from .build_image import setup_subparser as build_image_setup_subparser
File "/Users/jotompki/test-cli/env/lib/python3.9/site-packages/rpdk/core/build_image.py", line 11, in <module>
from .project import Project
File "/Users/jotompki/test-cli/env/lib/python3.9/site-packages/rpdk/core/project.py", line 15, in <module>
from rpdk.core.fragment.generator …
```
> Add ordered_set as a package dependency

- src/rpdk/core/data/schema/provider.definition.schema.v1.json
https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/pull/86
Description of changes: Allow replacement Strategy in the schema. This allows immutable singleton resources to update in the order of delete then create.
> Add replacement Strategy to schema

- src/rpdk/core/data_loaders.py
- tests/data/schema/invalid/invalid_nested_property_object_additionalProperties_true_warning.json
- tests/data/schema/invalid/invalid_pattern_properties_additionalProperties_true_warning.json
- tests/data/schema/valid/valid_nested_property_object_no_additionalProperties_warning.json
- tests/data/schema/valid/valid_pattern_properties.json
- tests/data/schema/valid/valid_pattern_properties_no_additionalProperties_warning.json
- tests/test_data_loaders.py
Currently, in the provider definition schema we do not restrict the structured property to specify the additionalProperties as false. Structured properties should define the additionalProperties as false otherwise properties with different case or pattern could not be caught during validation.
Tested by running the `cfn validate`
```
⋊> ~/c/NrqlAlertCondition on master ⨯ cfn validate                                                                                                                                                       
[Warning] Resource spec validation would fail from next major version. Provider should mark additionalProperties as false if the property is defined as a structured property. Please fix the warnings: 'additionalProperties' is a …
```
> Add additional checks on structured properties to not leak the additional properties to handlers during validation

- .github/workflows/schema-updater.yaml
[tested in my fork](https://github.com/PatMyron/cloudformation-cli/pull/1/files)
currently picks up https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/pull/84 and reverts https://github.com/aws-cloudformation/cloudformation-cli/pull/612 unless it's added there too
> automating CloudFormation Resource Provider Definition MetaSchema updates with Github actions

- README.md
- setup.cfg
- setup.py
- src/rpdk/core/fragment/generator.py
- src/rpdk/core/project.py
- src/rpdk/core/validate.py
- tests/data/sample_fragments/template_without_parameter_section.json
- tests/test_project.py
*Description of changes:* when calling `cfn validate` on a module, run `cfn-lint` on the fragment for extra validations.
(Future improvement: support `cfn validate --region` so that we can pass the `region` value to `cfn-lint`. Related: https://github.com/aws-cloudformation/cfn-python-lint/issues/607)
Sample output:
```bash
MacBook@ ~/Desktop/modules/cfnlint $ cat fragments/sample.json
{
"AWSTemplateFormatVersion": "2010-09-09",
"Resources": {
"S3Bucket": {
"Type": "AWS::S3::Bucket",
"DeletionPolicy": "Something",
"UpdateReplacePolicy": "Retain"
}
}
}
MacBook@ ~/Desktop/modules/cfnlint $ cfn validate
Module fragment is probably valid, but there are warnings/errors from cfn-lint (https://github.com/aws-cloudformation/cfn-python-lint):
DeletionPolicy should be …
```
> Call cfn-lint for module fragments

- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/contract/suite/handler_update.py
- tests/contract/test_resource_client.py
*Issue #, if available:* #626 
Problem: 
payload for update request was created by merging all properties from the resourceModel** and inputs_#_update
Fix: 
- create the payload by merging only unique identifiers i.e primaryIdentifiers and additionalIdentifiers from the resourceModel into inputs_#_update
- check that createOnly primaryIdentifier(s) are not changed between the resourceModel and inputs_#_update
**resourceModel is model returned after a successful create.
> Fix to copy only unique identifiers into update example

- .github/workflows/schema-updater.yaml
[Manual triggers with `workflow_dispatch`](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) in addition to [`cron schedule`](https://github.com/aws-cloudformation/cloudformation-cli/pull/647)
> enable manual CloudFormation Resource Provider Definition MetaSchema syncing

- .pylintrc
- setup.cfg
- src/rpdk/core/data_loaders.py
- tests/data/schema/valid/invalid_list_api_options_as_properties.json
- tests/data/schema/valid/invalid_readOnlyProperties_overlap.json
- tests/data/schema/valid/invalid_wildcard_handler_permissions.json
**resource types with LIST API options like `MaxResults`, `NextToken`, `Filters`, etc as properties of the resource itself:**
https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-licensemanager/pull/3
https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-iotwireless/pull/3
https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ssm/pull/75
```shell
botocore $ grep -h 'input_token' botocore/data/*/*/paginators-1.json | tr '[:upper:]' '[:lower:]' | sort | uniq -ic | sort -nr | head
1147       "input_token": "nexttoken",
328       "input_token": "marker",
40       "input_token": "pagetoken",
18       "input_token": "position",
16       "input_token": "nextmarker",
7       "input_token": "nextpagetoken",
5       "input_token": …
```
> catch common resource schema issues

- .coveragerc
- src/rpdk/core/project.py
- tests/test_project.py
Adding CLI version information in a metadata file named _cfn_metadata.json. This file will be included in the package artifact zip being uploaded. 
> Add cli version information in package artifact during cfn submit

- src/rpdk/core/project.py
- tests/test_project.py
Add project as a param when fetching plugin information, this is needed to get runtime version
> Add project reference when getting plugin information

- src/rpdk/core/contract/suite/handler_update_invalid.py
*Issue #, if available:* 
*Description of changes:* contract_update_non_existent_resource fails with the exception:
```Any createOnlyProperties specified in update handler input MUST NOT be different from their previous state```
The above issue was happening because the create model's primary Identifier was different from update model. 
https://github.com/aws-cloudformation/cloudformation-cli/blame/629b4767b46becdae168e934b33f65f87146b190/src/rpdk/core/contract/suite/handler_update_invalid.py#L54-L55
The above issue was introduced here: https://github.com/aws-cloudformation/cloudformation-cli/commit/49eac51bf8257b0b2cc63cc26c9338eff592d3e1
* Test result:
```
==================================================================================================================== test session …
```
> contract_update_non_existent_resource test fails with Assertion error

- src/rpdk/core/contract/suite/contract_asserts.py
- src/rpdk/core/contract/suite/handler_commons.py
*Issue #, if available:* https://github.com/aws-cloudformation/cloudformation-cli/issues/662
*Description of changes:* This Cr makes the inout == output comparison uniform for both create input == create output && create input == read output.
*Test:*
```
platform darwin -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /Users/anshikg/workspace/cloudformation-cli/env/bin/python3
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
hypothesis profile …
```
> making input equals to output comparison uniform

- setup.cfg
- setup.py
- src/rpdk/core/data_loaders.py
- tests/data/schema/valid/invalid_lowercase_property.json
- tests/data/schema/valid/invalid_non_ascii_chars.json
- tests/data/schema/valid/invalid_property_constraints.json
continuing https://github.com/aws-cloudformation/cloudformation-cli/pull/663, https://github.com/aws-cloudformation/cloudformation-cli/pull/668
fixes https://github.com/aws-cloudformation/cloudformation-cli/issues/459, https://github.com/aws-cloudformation/cloudformation-cli/issues/414
---
**[how to run new validations on all existing resource provider schemas](https://github.com/aws-cloudformation/cloudformation-cli/pull/604#issuecomment-756521889)**
---
* [incorrect min/max constraints](https://github.com/aws-cloudformation/cloudformation-cli/issues/414)
* [inconsistent property casing](https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/pull/77)
```bash
curl -s -N --compressed https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json …
```
> catch common resource schema issues in cfn validate

- src/rpdk/core/contract/suite/handler_commons.py
- src/rpdk/core/contract/suite/handler_update.py
*Description of changes:* prune read only properties from both input to create/update and output from create/update/read to avoid contract test failure
*Test*:
```
platform darwin -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /Users/anshikg/workspace/cloudformation-cli/env/bin/python3
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/anshikg/workspa …
```
> Prune read only properties from input & output

- src/rpdk/core/project.py
Currently it will only show `Project file not found` error message, it's hard to know which file is Project file and where it should be.
```
>cfn submit
Project file /Users/libruce/repos/mytest/.rpdk-config not found. Have you run 'init' or in a wrong directory?
```
> Refine error message if .rpdk-config doesn't exist

- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/contract/templates/transformation.template
- tests/contract/test_resource_client.py
*Description of changes:* Add Regex and OR support for property Transform
Property Transform uses regex to compare ARN and OR to support multiple conditions. This change helps contract test support these conditions and make sure we are at parity with drift.
> Add Regex and OR support for transform

- src/rpdk/core/contract/interface.py
- src/rpdk/core/fragment/generator.py
- tests/data/sample_fragments/template_with_date_in_version.yaml
- tests/fragments/test_generator.py
[Issue 692](https://github.com/aws-cloudformation/cloudformation-cli/issues/692)
Don't throw an internal error when template uses the version string without quotes
```
AWSTemplateFormatVersion: 2010-09-09
```
Instead of 
```
AWSTemplateFormatVersion: "2010-09-09"
```
> Issue-692 [Modules] Don't fail validation when version string with no quotes

- src/rpdk/core/contract/suite/handler_commons.py
- src/rpdk/core/contract/suite/handler_delete.py
The Cr has 2 changes:
* Fix the ```TypeError: list expected at most 1 arguments, got 2``` bu adding the 2 sets into one
* remove the check to see if deleted_model == create_output this not required as deleted_model and request are the same model. 
*Test:*
```
(env) 3c22fbb25c23:aws-cloudwatch-alarm anshikg$ cfn test --enforce-timeout 120
[Warning] Resource spec validation would fail from next major version. Provider should mark additionalProperties as false if the property is of object type and has properties or patternProperties defined in it. Please fix the warnings: 'additionalProperties' is a required property
Failed validating 'required' in schema['properties']['properties']['patternProperties']['^[A-Za-z0-9]{1,64}$']['allOf'][0]['de …
```
> fix the list and remove unneeded check for delete contract test

- fragments/sample.json
- src/rpdk/core/data/examples/module/sample.json
Enable Encryption in Modules example fragment, because that's good practice in S3
> Enable Encryption in Modules example fragment

- setup.cfg
- setup.py
- src/rpdk/core/cli.py
- src/rpdk/core/fragment/generator.py
- src/rpdk/core/fragment/lint_warning_printer.py
- src/rpdk/core/fragment/module_fragment_reader.py
- tests/data/sample_fragments/ec2withsub.yaml
- tests/fragments/test_generator.py
- tests/fragments/test_lint_warning_printer.py
- tests/fragments/test_module_fragment_reader.py
Issues #693 and #689 
* Using [cfn-flip](https://github.com/awslabs/aws-cfn-template-flip) to parse the Module fragments so we can support the full range of CFN yaml syntax. This is solving the problem that we can't currently parse templates like the one below:
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Resources:
EC2Instance:
Type: AWS::EC2::Instance
Properties:
ImageId: ami-09c5e030f74651050
UserData:
Fn::Base64: !Sub |
#!/bin/bash -e
sudo yum install -y https://s3.region.amazonaws.com/amazon-ssm-region/latest/linux_amd64/amazon-ssm-agent.rpm
sudo systemctl status amazon-ssm-agent
sudo systemctl enable amazon-ssm-agent
sudo systemctl start amazon-ssm-agent
```
* Apply cfn-lint on the original, unmodified module fragment file to avoid any false positives …
> [Modules] Support parsing Yaml fragments with CFN short forms

- README.md
It's more interesting to see if the master branch build is passing than the last release
> Show master branch badge, instead of release badge

- .gitignore
- src/rpdk/core/module/init_module.py
- tests/fragments/test_generator.py
- tests/jsonutils/area_definition_flattened.py
- tests/module/test_init_module.py
- tests/test_init.py
- tests/test_project.py
- tests/utils.py
Some modules tests were operating on the root folder of this repo and generating files there. This commit changes that to use temporary directories so no files are leaked.
> Prevent Modules unit tests from leaking files

- src/rpdk/core/invoke.py
*Description of changes:* When calling cfn invoke locally, the temporary credentials are printed out of the console. This could be a potential security issue. Redacted credentials from the console output. Following is the output when I run cfn invoke on my machine:
```
(env) 3c22fbb25c23:typescript anshikg$ cfn invoke CREATE create.json 
Resource schema is valid.
=== Handler input ===
{
"requestData": {
"callerCredentials": "<redacted>",
"resourceProperties": {
"Color": "000",
"Name": "000"
},
"previousResourceProperties": {},
"logicalResourceId": "2b62c178-dd3d-453e-aa67-1f0eb259b1ab"
},
"region": "us-east-1",
"awsAccountId": "594820947549",
"action": "CREATE",
"callbackContext": null,
"bearerToken": "2b62c178-dd3d-453e-aa67-1f0eb259b1ab"
}
=== Handler response …
```
> Redact credentials from invoke console output

- src/rpdk/core/data/schema/provider.definition.schema.v1.json
- src/rpdk/core/data_loaders.py
- tests/test_data_loaders.py
Adding `conditionalCreateOnlyProperties` to meta schema, so that resource providers could model properties that could not deterministically predict replacement/inline update.
Adding validation, as `conditionalCreateOnlyProperties` and `createOnlyProperties` must not overlap. 
> Adding conditionalCreateOnlyProperties to metaschema

- tests/data/sample_fragments/OpsWorks.json
- tests/data/sample_fragments/OpsWorksSchema.json
- tests/fragments/test_generator.py
Adding this over-assertive unit test for modules schema generation. Asserting on the exact schema that is currently generated for this fairly complex module, so that we have one more way of being notified when something about the schema generation changes. The schema generation is coupled to certain logic in the CFN server-side and we should be cautious when making changes.
The module fragment is taken from the official sample templates in the CFN documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/sample-templates-services-us-west-2.html#w2ab1c35c58c13c27
> Adding a unit test for module schema generation

- src/rpdk/core/contract/suite/handler_update_invalid.py
https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/pull/120#pullrequestreview-625828185
https://github.com/aws-cloudformation/cloudformation-cli/issues/527#issuecomment-680696823
> removing contract_update_create_only_property

- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/contract/suite/handler_commons.py
*Description of changes:* property Transform allows users to compare regex with live state from read handler. Regex comparison fails in input_equals_output method as  we were equating regex to live state rather than checking for regex match. This CR adds a check to compare regex rather than equating strings.
Lets say a customer adds the name of a property when creating the resource. This property name is updated to an ARN. propertyTransform property in the schema will allow one to define the arn regex to ensure this property is not falsely drifted.
```
document_input: {
"propertyName": "Name"
}
```
```
document_output: {
"propertyName": "arn:(aws)[-]{0,1}[a-z]{0,2}[-]{0,1}[a-z]{0,3}:ecs:[a-z]{2}[-]{1}[a-z]{4,10}[-]{1}[1-3]{1}:[0-9]{12}[:]{1}cluster/Name"
}
``` …
> support regex comparison for transformed values

- src/rpdk/core/contract/resource_client.py
- tests/contract/test_resource_client.py
*Description of changes:* Merging create model with update model to make sure we are fetching the read only properties.
*Test:*
```
(env) anshikg@3c22fbb25c23 aws-cloudwatch-alarm % cfn test --enforce-timeout 120                             
[Warning] Resource spec validation would fail from next major version. Provider should mark additionalProperties as false if the property is of object type and has properties or patternProperties defined in it. Please fix the warnings: 'additionalProperties' is a required property
Failed validating 'required' in schema['properties']['properties']['patternProperties']['^[A-Za-z0-9]{1,64}$']['allOf'][0]['dependencies']['patternProperties']:
{'$comment': 'An object cannot have both defined and undefined '
'properties; therefore, …
```
> Merge create and update model to get read only properties

- src/rpdk/core/contract/suite/handler_create.py
Remove the contract test ```contract_invalid_create``` which tries to create an invalid resource and expects the handler to fail. 
If an invalid request is made, the platform should throw an exception vs expected the handlers to throw the exception. In my opinion it is a redundant and error prone contract test which might cause more pain and failing contract test than usage. Therefore, removing this test from the contract test suite.
**Test**:
Ran the contract test for log::loggroup resource
```
(env) anshikg@3c22fbb25c23 aws-logs-loggroup % cfn test
Consider not manually maintaining large constantly evolving enums like instance types, lambda runtimes, partitions, regions, availability zones, etc. that get outdated quickly: [1, 3, 5, 7, …
```
> Remove contract_invalid_create contract test

- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/project.py
- tests/contract/test_resource_client.py
If the `additionalIdentifiers` property is present in a resource schema
the `generate_update_example` method in `resource_client` will not work,
because it checks for unique keys from the create_model and passes
`self._additional_identifiers_paths` to a method that expects a list of
tuples of string, whereas it receives a list of sets of tuples of
string and will fail with
```
AttributeError: 'tuple' object has no attribute 'split'
```
Instead, check if the key is in any of the additional identifiers.
Related issue
-------------
https://github.com/aws-cloudformation/cloudformation-cli/issues/731
> Fix update generation with additionalIdentifiers

- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/contract/suite/handler_commons.py
- tests/contract/test_resource_client.py
*Issue #, if available:* 
*Description of changes:* This CR avoids comparing nested properties which were not present in the input model provided to the handler. This is done to mimic the drift functionality and avoid failing contract test for expected behavior.
In the below CR I am recursively checking the model of the input and output and comparing the properties present in input with output model and asserting only if a property present in input model is not present/changed in the output model.
For now, the functionality for un order types has been removed as this not supported in the back end service.
*Test:* Ran contract test for resources which failed this condition
```
=================================================================================================================== …
```
> Add support for nested comparison

- src/rpdk/core/contract/suite/handler_commons.py
*Description of changes:*.   Currently it uses shallow copy for model comparison. However,  for any read only property is nested, it will modify the actual model during the comparison.  For example, if a primary ID is nested property,  the contract test will break as the primary id will be pruned in this method.
Verified using a nested primary ID, now the primary Id can pass to delete handler correctly.
> Use deep copy for model compare

- src/rpdk/core/contract/resource_client.py
- tests/contract/test_resource_client.py
*Description of changes:* This change ensure we compare a list of primitive types correctly. If a list exists, compare_list method is called which in turn calls the compare method of each index. This value doe snot have a key, just has a value which needs to compared using the else block mentioned below 
*Test:*
```
============================================================================================================= 1 passed, 13 deselected in 31.56s ==============================================================================================================
(env) anshikg@3c22fbb25c23 aws-cloudwatch-alarm % cfn test --enforce-timeout 120                             
Incorrect JSON schema keyword(s) {'patternProperties'} for type: string for property: …
```
> Add comparison for primitive type

- src/rpdk/core/contract/interface.py
A new error of type `INVALID_TYPE_CONFIGURATION ` is added to aws sdk which seems to fail test_handler_error_code_enum_matches_sdk test. Adding the new error type to the enum so that the test passes.
> Update HandlerErrorCode with new InvalidTypeConfiguration value

- src/rpdk/core/data/managed-upload-infrastructure.yaml
Remove CloudFormation access to S3 via ArtifactCopyPolicy and KMS secret access since it is not used anymore
Tested by installing local changes in cloudformation cli and using cloudwatch-alarm resource to register in private account and test creating a stack -
> Remove CloudFormation access to S3 via ArtifactCopyPolicy and KMS access

- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/jsonutils/utils.py
- tests/contract/test_resource_client.py
*Issue #, if available:* https://github.com/aws-cloudformation/cloudformation-cli/issues/811
Collection Comparison for contract tests. Method `test_input_equals_output` contains a naive comparison of the collections, which generates a false positive for unordered sets.
Change: instead of comparing lists by values, added `compare_collection`. If `insertionOrder` is `False` then transform list items (since it's json each item is scalar/array/json) into a set of hash values, which does naive comparison after that. For hashing I'm using MD5, which is not secure hashing but provides a good hashing for contract test purpose.
> [BugFix] Collection Comparison for Contract Tests

- src/rpdk/core/boto_helpers.py
- tests/test_boto_helpers.py
Increase Boto assumeRole duration to 6 hours
> Increase Boto assumeRole duration to 6 hours

- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/jsonutils/utils.py
- tests/contract/test_resource_client.py
- tests/jsonutils/test_utils.py
Previously, contract tests could not prune an attribute from *all* sequence members, but pruning an attribute for a specific attribute was doable (by specifying a valid index in the path to prune). If supplying an asterisk (`*`) in the path for a sequence, the `traverse` method would run into a ValueError:
```
~/.virtualenvs/local_cfn/lib/python3.8/site-packages/rpdk/core/jsonutils/utils.py:114: in traverse
part = int(part)
E   ValueError: invalid literal for int() with base 10: '*'
```
This pull request adds support for pruning attributes for all sequence members, when the index provided for the sequence is `*`.
(NOTE: it could easily be any other unpack identifier that isn't a valid property name, but asterisk felt like a good choice)
An example of a schema with readonly sequence …
> Update prune_properties to support pruning attributes for all sequence members

- src/rpdk/core/data/schema/provider.definition.schema.v1.json
- tests/test_data_loaders.py
Add nonPublicProperties and nonPublicDefinitions lists of JSONPointers in metaschema. Adding top level lists to allow hidden property and definition paths to be accepted.
> Add nonPublicProperties and nonPublicDefinitions lists of JSONPointers

- setup.py
jsonschema 4.0 introduced a breaking change that we were depending on. I have pinned the json schema to any version before 4.0 (and after the existing 3.0.1
```(.venv) Feder08:~/environment $ cfn init
Traceback (most recent call last):
File "/home/ec2-user/environment/.venv/bin/cfn", line 5, in <module>
from rpdk.core.cli import main
File "/home/ec2-user/environment/.venv/lib64/python3.7/site-packages/rpdk/core/cli.py", line 12, in <module>
from .build_image import setup_subparser as build_image_setup_subparser
File "/home/ec2-user/environment/.venv/lib64/python3.7/site-packages/rpdk/core/build_image.py", line 11, in <module>
from .project import Project
File "/home/ec2-user/environment/.venv/lib64/python3.7/site-packages/rpdk/core/project.py", line 15, in <module>
from …
```
> fix: breaking change in jsonschema

- src/rpdk/core/fragment/module_fragment_reader.py
*Description of changes:* Add `.template` to allowed fragment extentions.
`.template` is a pretty common extension for CloudFormation templates. In fact, AWS publishes several templates with that extension in various GitHub repositories. It therefore ought to be allowable as a fragment filename extension.
> Add .template to allowed extensions and fix typo in error message

- setup.py
N/A
I noticed the tests encounter this failure in codebuild:
```
Container] 2021/12/06 19:53:04 Running command pip3 install --upgrade pip setuptools wheel > /dev/null
[Container] 2021/12/06 19:53:08 Running command pip3 install cloudformation-cli cloudformation-cli-java-plugin cloudformation-cli-go-plugin cloudformation-cli-python-plugin cloudformation-cli-typescript-plugin > /dev/null
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
serverlessrepo 0.1.9 requires pyyaml~=5.1, but you have pyyaml 6.0 which is incompatible.
awscli 1.18.49 requires PyYAML<5.4,>=3.10; python_version != "3.4", but you have pyyaml 6.0 …
```
> Add upperbound for PyYAML dependency

- src/rpdk/core/contract/hook_client.py
- src/rpdk/core/project.py
- tests/contract/test_hook_client.py
Fixed some `cfn test` bugs for `HOOK`  type projects:
* Prune `createOnlyProperties` and `readOnlyProperties` from target schema when generating schema strategy for target
* Fix bug where CFN DescribeType API would still be called even if local target info was provided
* Log exact target type name that failed contract tests to help debug process
> Updated hook contract tests to prune target schema properties

- src/rpdk/core/contract/hook_client.py
- tests/contract/test_hook_client.py
Updating hook contract test client to only setup a schema strategy for the hook's target if no input is given
> Setup Hook target schema strategy only if no input is provided for contract tests

- src/rpdk/core/data/managed-upload-infrastructure.yaml
This change added DeletionPolicy and UpdateReplacePolicy as part of the Deployment Safety Campaign
S3 buckets are Stateful resources therefore require DeletionPolicy and UpdateReplacePolicy. 
> add deletionPolicy and replacepolicy for managedUploadinfra stack

- .pre-commit-hooks.yaml
As a CFN module developer I want to prevent commits to my module repo that have drift between the schema and template fragment.
This PR makes the cfn cli available as a [pre-commit hook](https://pre-commit.com/#new-hooks) that can be used in module projects by adding a `.pre-commit-config.yaml` as follows:
```
repos:
- repo: https://github.com/aws-cloudformation/cloudformation-cli
rev: v0.2.26
hooks:
- id: cfn-module-generate
```
> add pre-commit hook for modules

- src/rpdk/core/data/examples/hook/sse.verification.v1.json
Updated the example hook schema to target an `AWS::S3::Bucket` to provide a real world example after initiating a hook project
Related PRs:
* https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/398
* https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/pull/188
> Update example hook schema to target real resource types

- src/rpdk/core/data/schema/base.definition.schema.v1.json
- src/rpdk/core/data/schema/provider.definition.schema.modules.v1.json
- src/rpdk/core/data_loaders.py
- tests/test_data_loaders.py
*Description of changes:* Add custom tag arrayType
arrayType is only applicable for property of type array. When set to AttributeList, it indicates that the array is of nested type objects, and when set to Standard it indicates that the array consists of primitive types.
> Add custom property arrayType

- src/rpdk/core/project.py
- tests/test_project.py
fix #907 
- Remove runtime checks from the core library.  This should be enabled by the plugins and not the core package
> fix(core) - Remove runtime checks and leave it to the plugin

- src/rpdk/core/data/managed-upload-infrastructure.yaml
Policy was enforced in https://github.com/aws-cloudformation/cloudformation-cli/pull/389, but another bucket was added later in https://github.com/aws-cloudformation/cloudformation-cli/pull/396. Enforcing SecureTransport for that bucket as well
---
> Enforce SecureTransport policy on AccessLogsBucket

- tests/contract/test_hook_client.py
- tests/contract/test_type_configuration.py
#912 
- Trying to fix the below error that happens randomly
```
=================================== FAILURES ===================================
_______________________________ test_call_docker _______________________________
@staticmethod
def get_hook_configuration():
type_configuration = TypeConfiguration.get_type_configuration()
if type_configuration:
try:
return type_configuration.get("CloudFormationConfiguration", {})[
>                   "HookConfiguration"
]["Properties"]
E               KeyError: 'HookConfiguration'
/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/rpdk/core/contract/type_configuration.py:48: KeyError
The above exception was the direct cause of the following exception:
def test_call_docker(): …
```
> fix(tests) - clean up docker random hook failures

- src/rpdk/core/test.py
- tests/test_test.py
Closes #876 
`cfn test` fails with Unhandled exception on Windows.  This is due to using NamedTemporaryFile which per Python docs does NOT work the same in Windows. 
```
Whether the name can be used to open the file a second time, while the named temporary file is still open,
varies across platforms (it can be so used on Unix; it cannot on Windows).
```
https://docs.python.org/3.9/library/tempfile.html#tempfile.NamedTemporaryFile
Setting `delete=False` as workaround.
*NOTE* - Temporary file must be explicitly cleaned up after temporary_ini_file() is called!
Fix being tracked here https://github.com/python/cpython/issues/58451
> fix(cli): `cfn test` broken on Windows - NamedTemporaryFile issue

- .pre-commit-config.yaml
Pre-commit config file updated to support newest versions that support Python 3.6
> Chore(precommit): update precommit versions to latest that supports Python 3.6

- src/rpdk/core/contract/resource_generator.py
- src/rpdk/core/data_loaders.py
- tests/contract/test_resource_generator.py
- \w, \W, \b, \B, \d, \D, \s and \S flags in regex should be ASCII based not unicode
- Unicode is the default in python so this switches it to be ascii based
> fix(schema) - Use ASCII characters for \w in pattern regex

- .github/workflows/pypi-release.yaml
Closes #936 
Pypi has deprecated "master" and now uses pypa/gh-action-pypi-publish@release/v1 syntax.  Updated github action to reflect this change
> chore(CD): Update pypi GHA to new syntax

- src/rpdk/core/project.py
- tests/test_project.py
- Add `strict_timestamps` to False when creating a ZipFile on python 3.8 and greater
replaces pr #600 
> fix(core) - Ignore timestamp issues when creating a ZipFile on py3.8 and greater

- src/rpdk/core/contract/hook_client.py
- src/rpdk/core/contract/interface.py
- src/rpdk/core/contract/suite/hook/handler_pre_create.py
- src/rpdk/core/contract/suite/hook/handler_pre_delete.py
- src/rpdk/core/contract/suite/hook/handler_pre_update.py
- src/rpdk/core/contract/suite/hook/hook_handler_commons.py
- src/rpdk/core/contract/type_configuration.py
- src/rpdk/core/data/pytest-contract.ini
- src/rpdk/core/data_loaders.py
- src/rpdk/core/exceptions.py
- src/rpdk/core/generate.py
- src/rpdk/core/project.py
- src/rpdk/core/templates/hook-docs-readme.md
- src/rpdk/core/type_name_resolver.py
- src/rpdk/core/type_schema_loader.py
- tests/contract/test_hook_client.py
- tests/contract/test_interface.py
- tests/test_data_loaders.py
- tests/test_generate.py
- tests/test_project.py
- tests/test_type_name_resolver.py
- tests/test_type_schema_loader.py
This PR adds support for hooks with wildcard targets. This allows hooks to be registered with wildcard target names which are matched to hook target types during invocation.
For example, the target name `AWS::S3*::Bucket*` would resolve and be invoked by the following resource types:
* `AWS::S3::Bucket`
* `AWS::S3::BucketPolicy`
* `AWS::S3Outpost::Bucket`
* `AWS::S3Outpost::BucketPolicy`
Related PRs:
* https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/406
* https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/pull/224
> Add support for Wildcard Hook Targets

- .gitattributes
- setup.py
- src/rpdk/core/contract/hook_client.py
- src/rpdk/core/templates/docs-readme.md
- src/rpdk/core/templates/docs-subproperty.md
- src/rpdk/core/templates/hook-docs-readme.md
Closes #940 
Closes #938 
Closes #899 
Closes #864 
Jinja2 upgraded away from setuptools and pkg_resources, this caused a slight change in PackageLoader.  Updated Jinja2 template syntax and PackageLoader in contract/hooks_client to compensate and unpin Jinja2 and MarkupSafe.
> fix(jinja2): upgrade jinja2 and markupsafe

- .github/workflows/pr-ci.yaml
Github actions have removed support for Python 3.6.
> remove python 3.6 from github actions

- src/rpdk/core/contract/suite/resource/handler_update_invalid.py
Fix warning below when running Contract tests
Pytest warning when running contract tests:
```
resource/handler_update_invalid.py::contract_update_without_create
/opt/homebrew/lib/python3.10/site-packages/_pytest/python.py:199: PytestReturnNotNoneWarning: Expected None, but resource/handler_update_invalid.py::contract_update_without_create returned <HandlerErrorCode.NotFound: 'NotFound'>, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
warnings.warn(
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
> Pytest warning fix for contract test contract_update_without_create

- src/rpdk/core/data/managed-upload-infrastructure.yaml
Fixes #985
Update configuration for the logging bucket:
- use a bucket policy instead of an ACL; see **Grant permissions to the logging service principal using a bucket policy** in [Permissions for log delivery](https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html#grant-log-delivery-permissions-general);
- use `AES256` instead of the current `SSE-KMS` setting for the log bucket; see considerations on the default bucket encryption on the target bucket with `AES256` (`SSE-S3`) in [Enabling Amazon S3 server access logging](https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html) (where I note: _You can use [default bucket …
> Update configuration for the logging bucket.

- src/rpdk/core/data/examples/hook/targets/aws-s3-bucket.json
- src/rpdk/core/hook/init_hook.py
- src/rpdk/core/type_name_resolver.py
- tests/hook/test_init_hook.py
- tests/test_init.py
- tests/test_project.py
* https://github.com/aws-cloudformation/cloudformation-cli/issues/959
* https://github.com/aws-cloudformation/cloudformation-cli/issues/960
Updated the `cfn init` command for `HOOK` type projects to only allow projects to be initialized with language plugins that support `HOOK` types.
This PR also fixes an issue with error being thrown when project was initialized with no AWS credentials set
> Update hook project init to use only plugins that support hooks and fixing issue with init when no creds are specified

- src/rpdk/core/submit.py
Closes #969 
Add in CLI packaging overrides to submit command for `cfn submit --no-docker` and `cfn submit --use-docker`
This will override the use_docker settings in .rpdk-config file when building the package.
> Add in no-docker and use-docker override to submit command

- src/rpdk/core/data/managed-upload-infrastructure.yaml
The two buckets (ArtifactBucket and AccessLogsBucket) created by the stack CloudFormationManagedUploadInfrastructure do not have the Block Public Access setting enabled.. 
**This Pull Request to enable block public access settings to those buckets.**
> Block public access to Artifact/AccessLogs Buckets

- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/contract/suite/resource/handler_commons.py
- src/rpdk/core/contract/suite/resource/handler_create.py
- src/rpdk/core/contract/suite/resource/handler_update.py
- tests/contract/test_resource_client.py
Improving logging for Ctv1 
Testing : 
Unit testing 
Pre-commit hooks are successful 
Screenshots :
> Improving logging for Ctv1

- src/rpdk/core/data/managed-upload-infrastructure.yaml
Fix #1001
For the logs bucket described in the template, update its lifecycle configuration as follows:
- replace the existing rule with `Status: Enabled` and `ExpirationInDays: 3653` with the same content, and:
- add a name for the rule, for consistency;
- add configuration to expunge noncurrent objects (as the logs bucket is versioned) after one day they became noncurrent (in the case of this versioned bucket with `ExpirationInDays: 3653`, objects will be made noncurrent after 10 years or 3653 days);
- add another, separate rule to expunge expired object delete markers.
> Update lifecycle config for the logs bucket.

- setup.py
- src/rpdk/core/jsonutils/inliner.py
- src/rpdk/core/jsonutils/renamer.py
- Update jsonschema to keep up with SAM
> Update jsonschema to keep up with other tools

- setup.py
PR #990 pins the version of cfn-lint without much documentation or linking to bugs.  This will revert that pin as there isn't much reason to have the public version of this pinned down.
> Fix pin to cfn-lint

- setup.py
- src/rpdk/core/data/schema/provider.definition.schema.v1.json
- src/rpdk/core/jsonutils/inliner.py
- tests/jsonutils/test_inliner.py
- tests/test_data_loaders.py
> Handler schema definition

- src/rpdk/core/cli.py
- src/rpdk/core/extensions.py
- src/rpdk/core/plugin_base.py
- src/rpdk/core/plugin_registry.py
- tests/test_cli.py
- tests/test_extensions.py
- tests/test_plugin_base.py
- tests/test_plugin_registry.py
*Issue #, if available:* NA
This change enables custom plugins to be developed under the `rpdk.v1.extensions` entrypoint to extend `cfn` functionality. E.g. developing a new `hello` command:
```
cfn hello --name Adrian
Hello, Adrian!
```
In this change, I introduce the `ExtensionPlugin` abstract base class, which has 2 methods. `command_name` determines what the command will be (e.g. `hello` in the above example). This registers a subparser under `cfn`. The second method is `setup_parser` which should be implemented in the child class to setup any arguments and behaviors required (e.g. `--name` parameter and printing `Hello, Adrian!` in examble above)
The way a new extension can be setup is the same way as other plugins already developed, where you simply `pip …
> Support for extending cfn cli with custom commands

- src/rpdk/core/invoke.py
- tests/test_invoke.py
This is for the use case where we are leveraging cfn invoke.
Before the fix only the callbackContext was passedin leading to a situation where if the model is updated and the handler emits a progress event we would end up losing recoding the updates that were made (and making the handler fail for those instances).  
One such example is when we are creating a resources and there are multiple API calls needed to materialize this resource with a progress event being emitted between this API calls and one of the later API calls needed info returned by the earlier calls and persisted in the model.
Validation:
seed isort known_third_party.............................................Passed
isort....................................................................Passed …
> Fix prepare_payload_for_reinvocation in invoke

- src/rpdk/core/contract/resource_client.py
This PR adds a json dump of inputs and outputs to the assertion message when the returned model doesn't match what was submitted.
> Add inputs and outputs to assertion message

- setup.py
botocore version 1.31.17 has tlv, needed to run contract test in tlv.
> require botocore version 1.31.17, as it has tlv

- src/rpdk/core/test.py
- tests/test_test.py
Adding a regex based exports replacement, as it is a less expensive manipulation. The change finds `{{ variable }}` pattern that jinja supports but verifies that variable is compliant with [stack export naming convention](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html). 
Example:
overrides.json
```
{
"CREATE": {
"/SubnetId": "{{ subnetID }}"
}
}
```
rendered overrides.json
```
{
"CREATE": {
"/SubnetId": "subnet-0bc6136e"
}
}
```
> Adding regex based exports replacement

- src/rpdk/core/project.py
- tests/data/schema/hook/valid/valid_hook_configuration_with_array_items.json
- tests/data/schema/hook/valid/valid_hook_configuration_without_array_items.json
- tests/test_project.py
Fix for documentation generation when no `items` key for a schema property of `array` type is present. When running `cfn generate`, for example against a schema of a CloudFormation hook that is missing the `items` node for a given property of `array` type, while the schema validation succeeds, the document generation logic fails with a `KeyError` because it assumes the `items` node is present in the input data:
```
[...]
if "$ref" in prop["items"]:
~~~~^^^^^^^^^
KeyError: 'items'
```
This change fixes this behavior by leaving the schema validation unchanged, and by defaulting to an empty map for `items` if `items` itself is not present in the input data. Proposed changes also include a warning message for the user to take action if …
> Fix for docs generation when no items key for a schema property of array type is present.

- requirements.txt
- Version 8 of pytest is causing issues with the patches builtin.open calls resulting in the tests to fail
> Issues with pytest 8

- .pylintrc
- src/rpdk/core/boto_helpers.py
- src/rpdk/core/contract/hook_client.py
- src/rpdk/core/contract/resource_client.py
- src/rpdk/core/test.py
- tests/contract/test_hook_client.py
- tests/contract/test_resource_client.py
- tests/test_boto_helpers.py
- tests/test_test.py
Adding headers in STS Calls for Confused Deputy to accept account id and the source ARN
> Adding headers in STS Calls for Confused Deputy

- src/rpdk/core/data/schema/base.definition.schema.v1.json
- tests/test_data_loaders.py
Adds the option to add `relationshipRef` to properties of a resource type.
> add relationshipRefs into the schema for validation

- setup.cfg
- setup.py
- src/rpdk/core/project.py
- tests/test_project.py
Add canary file generation functionality for Patch Operation canaries from contract test inputs.
canarySettings will be shared with generating Create Operation canaries. 
Testing Scenarios:
1. Validate that the correct number of output files are generated. Validated that file naming and structure are correct.
2. Validate that an existing field in the `CreateInputs` will be updated by a `replace`, `add` or `remove` operation in `PatchInputs`. 
3. Validate that only `replace`, `add` and `remove` operations result in an update. Other operations such as `move`, `copy` and `test` are ignored.
4. Validate that a field can be updated if it was not included in `CreateInputs` but included in `PatchInputs` for `add` and `replace` operations. 
5. …
> Implement canary file generation functionality from contract test PatchInputs

- src/rpdk/core/project.py
- tests/test_project.py
- Remove `file_generation_enabled` from `canarySettings`. If the canarySettings field is provided with an empty object, canaries will be generated with `contract_test_file_names: [input1.json]` default. If canarySettings are removed from .rpdk-config, no canary generation will occur. 
- Improved logging will simplify debugging canary autogeneration. 
- Add a warning log when `canarySettings` are provided but empty
- Add Logging at `info` level for skipping, starting, and finishing canary autogeneration
- Add Logging at the `debug` level for loading contract test inputs and writing canary file outputs. 
```
"canarySettings": {
"contract_test_file_names": ["inputs1.json"]
}
```
```
#positive case at Debug Log Level
% cfn generate -v -v -v …
```
> Add logging for canary auto generation and refactor canarySettings

- src/rpdk/core/generate.py
- src/rpdk/core/project.py
- tests/test_project.py
- Canary auto generation will be disabled for empty canary settings. This is intended to prevent auto generation when a key is added to the `.rpdk-config` when providers are upgrading their rpdk version set.
- Add an argument `local-code-generation` to the `cfn generate` command to enable canary auto generation. This intended to restrict canary autogeneration to specific development use cases. Canary auto-generation should not occur for remote builds. 
Unit Test Cases:
- Canary autogeneration will not occur if the `local-code-generation` flag is missing or False. 
- Add `local-code-generation=True` to existing unit tests
> Refactor canary auto-generation cli semantics

- src/rpdk/core/data_loaders.py
- src/rpdk/core/project.py
- src/rpdk/core/validate.py
- tests/test_project.py
These changes are made as part of Registration Improvement efforts.
This pull request is to add validations used in MPR into RPDK for `cfn validate`, and testing to support the changes.
(There is also a formatting change in `generate_docs()` that was modified by Black code formatter and does not contribute to any functionality changes)
This includes:
- checking the size of the RPDK config
- checking the size of the TypeConfiguration schema
- checking for a valid protocol version
Validations that were not included are:
- checks done in Schema Guard Rail
- checks between the configuration and the request (done during registration)
- checks for resource type relations (involves server-side calls to describe type)
By submitting this pull …
> Add mpr validations to cfn validate with supporting tests.
